services:
  backend:
    build: .

    ports:
      - "3000:3000"

    volumes:
      - .:/app
      - /app/node_modules

    env_file:
      - .env.docker

    depends_on:
      - postgres

  postgres:
    image: postgres:16

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: careerfit_dev

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: